### ISSUE TITLE
US14: Open/Close Doors

### ISSUE THREAD

**Issue by L3CH3R0** [Kadestery/The-FireWalls#13]
As a user or a smart home module, I want to open or close doors within the smart home system to simulate the movement of people or automate security protocols.

**Tasks**

- [ ] Send a command to the system to open or close a specific door.
- [ ] The system validates the sender's authorization.
- [ ] Upon validation, the system executes the command.
- [ ] The status of the door is updated in the system.
