### ISSUE TITLE
US15: Open/Close Windows

### ISSUE THREAD

**Issue by L3CH3R0** [Kadestery/The-FireWalls#15]
As a user or smart home module, I want the ability to open or close windows within the smart home to manage ventilation and temperature or enhance security.

**Tasks**

- [ ] Issue a command to the system to open or close a window.
- [ ] The system confirms the sender's authorization to perform this action.
- [ ] If authorized, the command is executed, changing the window's state.
- [ ] A confirmation of the state change is provided.
