### ISSUE TITLE
US16: On/Off Lights

### ISSUE THREAD

**Issue by L3CH3R0** [Kadestery/The-FireWalls#16]
As a user or smart home module, I want to turn the lights on or off within the smart home environment to create different atmospheres or save energy.

**Tasks**

- [ ] Send a command to turn the lights on or off.
- [ ] The system checks the authorization of the command sender.
- [ ] Upon successful authorization, the light state is changed as commanded.
- [ ] The system provides a confirmation of the change.
